In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests

In [2]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

.\aum_by_fund_house.csv
.\benchmark_indices.csv
.\category_inflows.csv
.\fund_master.csv
.\industry_folio_count.csv
.\investor_transactions.csv
.\kpi_summary.csv
.\monthly_sip_inflows.csv
.\nav_history.csv
.\portfolio_holdings.csv
.\scheme_performance.csv
.\.ipynb_checkpoints\fund_master-checkpoint.csv
.\.vscode\extensions\ms-mssql.mssql-1.43.0\sqltoolsservice\6.0.20260527.1\Portable\Data\DBCloudInput.csv
.\.vscode\extensions\ms-mssql.mssql-1.43.0\sqltoolsservice\6.0.20260527.1\Portable\Data\MICloudInput.csv
.\.vscode\extensions\pranaygp.vscode-css-peek-4.4.3\client\node_modules\import-in-the-middle\LICENSE-3rdparty.csv
.\AppData\Local\Programs\Microsoft VS Code\7e7950df89\resources\app\node_modules\@vscode\codicons\dist\codicon.csv
.\AppData\Local\Programs\Microsoft VS Code\7e7950df89\resources\app\node_modules\@vscode\codicons\_iconCloud\categories.csv
.\AppData\Local\Programs\Microsoft VS Code\7e7950df89\resources\app\node_modules\@vscode\codicons\_iconCloud\descriptions.csv
.\AppData\Local\Programs\Microsoft VS Code\7e7950df89\resources\app\node_modules\@vscode\codicons\_iconCloud\keywords.csv
.\AppData\Local\Programs\Microsoft VS Code\7e7950df89\resources\app\node_modules\@vscode\codicons\_iconCloud\metaphors.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\matplotlib\mpl-data\sample_data\data_x_x2_x3.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\matplotlib\mpl-data\sample_data\msft.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\matplotlib\mpl-data\sample_data\Stocks.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-arccos.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-arccosh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-arcsin.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-arcsinh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-arctan.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-arctanh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-cbrt.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-cos.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-cosh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-exp.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-exp2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-expm1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-log.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-log10.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-log1p.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-log2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-sin.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-sinh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-tan.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\core\tests\data\umath-validation-set-tanh.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\mt19937-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\mt19937-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\pcg64-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\pcg64-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\pcg64dxsm-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\pcg64dxsm-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\philox-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\philox-testset-2.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\sfc64-testset-1.csv
.\AppData\Local\Programs\Python\Python310\Lib\site-packages\~umpy\random\tests\data\sfc64-testset-2.csv
.\AppData\Roaming\Python\Python310\site-packages\tornado\test\csv_translations\fr_FR.csv
.\Downloads\Amazon-Bestseller-Dataset.csv
.\Downloads\car_purchase_data - Copy.csv
.\Downloads\car_purchase_data.csv
.\Downloads\diabetes.csv
.\Downloads\heart_disease_data (1).csv
.\Downloads\incounse_order.csv
.\Downloads\Insta_history (1).csv
.\Downloads\Insta_history.csv
.\Downloads\Nifty 50 Historical Data.csv
.\Downloads\XXXPS3152X_2022_23_AIS_TDS-TCS_16122023.csv
.\Downloads\creditcard.csv\creditcard.csv
.\Downloads\Final year project\diabetes.csv
.\Downloads\Final year project\heart_disease_data (1).csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\business_insights.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\processed\clean_nav.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\processed\clean_performance.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\processed\clean_transactions.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\processed\dashboard_dataset.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\processed\kpi_summary.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\aum_by_fund_house.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\benchmark_indices.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\category_inflows.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\fund_master.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\hdfc_top100_nav.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\industry_folio_count.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\investor_transactions.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\monthly_sip_inflows.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\nav_history.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\portfolio_holdings.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\scheme_performance.csv
.\OneDrive\Desktop\bluestock_mf_capstone\data\raw\{name}.csv
.\OneDrive\Desktop\bluestock_mf_capstone\report\data_dictionary.csv
.\OneDrive\Desktop\New folder (2)\blackfridaysaleprediction\BlackFridaySales.csv
.\OneDrive\Desktop\pull from github\Black-Friday-Sales-Prediction\Data\BlackFridaySales.csv
.\OneDrive\Desktop\pull from github2\blackfridaysaleprediction\BlackFridaySales.csv
.\OneDrive\Desktop\recosso_v3\recosso_project\media\report.csv
.\OneDrive\Documents\Insta_history (1).csv

In [3]:
import os
print(os.listdir())

['.anaconda', '.atom', '.bash_history', '.conda', '.config', '.continuum', '.copilot', '.git', '.gitconfig', '.Icecream Screen Recorder', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.lesshst', '.m2', '.matplotlib', '.ms-ad', '.node_repl_history', '.vscode', '.vscode-shared', '01_data_ingestion.ipynb', '02_data_cleaning.ipynb', '03_exploratory_data_analysis.ipynb', '04_kpi_and_data_modeling.ipynb', '3D Objects', 'AppData', 'Application Data', 'aum_by_fund_house.csv', 'benchmark_indices.csv', 'bluestock_mf.db', 'category_inflows.csv', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'Favorites', 'fund_master.csv', 'industry_folio_count.csv', 'investor_transactions.csv', 'kpi_summary.csv', 'Links', 'Local Settings', 'log', 'monthly_sip_inflows.csv', 'Music', 'My Documents', 'nav_history.csv', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf', 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{a54c6538-065a-11f1-a7ca-ec2e98492838}.TM.blf', 'NTUSER.DAT{a54c6538-065a-11f1-a7ca-ec2e98492838}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{a54c6538-065a-11f1-a7ca-ec2e98492838}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'online_batch', 'portfolio_holdings.csv', 'PrintHood', 'ReactProjects', 'Recent', 'Saved Games', 'scheme_performance.csv', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Videos']

In [4]:
import pandas as pd

In [5]:
fund_master = pd.read_csv('fund_master.csv')

In [6]:
fund_master.head()
fund_master.shape

(40, 15)

In [7]:
aum_by_fund_house = pd.read_csv('aum_by_fund_house.csv')

In [8]:
portfolio_holdings = pd.read_csv('portfolio_holdings.csv')
benchmark_indices = pd.read_csv('benchmark_indices.csv')
category_inflows = pd.read_csv('category_inflows.csv')
industry_folio_count = pd.read_csv('industry_folio_count.csv')
investor_transactions = pd.read_csv('investor_transactions.csv')
monthly_sip_inflows = pd.read_csv('monthly_sip_inflows.csv')
nav_history = pd.read_csv('nav_history.csv')
scheme_performance = pd.read_csv('scheme_performance.csv')

In [9]:
scheme_performance.shape

(40, 19)

In [10]:
datasets = {
    "fund_master": fund_master,
    "nav_history": nav_history,
    "aum_by_fund_house": aum_by_fund_house,
    "benchmark_indices": benchmark_indices,
    "category_inflows": category_inflows,
    "industry_folio_count": industry_folio_count
}

summary = []

for name, df in datasets.items():
    summary.append([
        name,
        df.shape[0],
        df.shape[1]
    ])

summary_df = pd.DataFrame(
    summary,
    columns=["Dataset","Rows","Columns"]
)

summary_df

                Dataset   Rows  Columns
0           fund_master     40       15
1           nav_history  46000        3
2     aum_by_fund_house     90        5
3     benchmark_indices   8050        3
4      category_inflows    144        3
5  industry_folio_count     21        6

In [11]:
fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [12]:
fund_master['fund_house'].unique()

array(['SBI Mutual Fund', 'HDFC Mutual Fund', 'ICICI Prudential MF',
       'Nippon India MF', 'Kotak Mahindra MF', 'Axis Mutual Fund',
       'Aditya Birla Sun Life MF', 'UTI Mutual Fund', 'Mirae Asset MF',
       'DSP Mutual Fund'], dtype=object)

In [13]:
fund_master['fund_house'].nunique()

10

In [14]:
fund_master['category'].value_counts()

category
Equity    34
Debt       6
Name: count, dtype: int64

In [15]:
fund_master['sub_category'].value_counts()

sub_category
Large Cap          14
Mid Cap             7
Small Cap           6
Liquid              3
Gilt                2
Flexi Cap           2
Short Duration      1
Value               1
Index/ETF           1
Index               1
Large & Mid Cap     1
ELSS                1
Name: count, dtype: int64

In [16]:
fund_master['risk_category'].value_counts()

risk_category
Moderate           16
High                8
Very High           6
Low                 6
Moderately High     4
Name: count, dtype: int64

In [17]:
import requests

url = "https://api.mfapi.in/mf/125497"

response = requests.get(url)

data = response.json()

In [18]:
data.keys()

dict_keys(['meta', 'data', 'status'])

In [19]:
nav_df = pd.DataFrame(data['data'])

In [20]:
nav_df.head()

         date        nav
0  03-07-2026  207.34610
1  02-07-2026  208.53730
2  01-07-2026  206.47780
3  30-06-2026  206.83550
4  29-06-2026  205.10350

In [21]:
nav_df.to_csv(
    r"C:\Users\shub2\OneDrive\Desktop\bluestock_mf_capstone\data\raw\hdfc_top100_nav.csv",
    index=False
)

In [22]:
funds = {
    "SBI_Bluechip":119551,
    "ICICI_Bluechip":120503,
    "Nippon_LargeCap":118632,
    "Axis_Bluechip":119092,
    "Kotak_Bluechip":120841
}

In [ ]:
for name, code in funds.items():

    url = f"https://api.mfapi.in/mf/{code}"

    response = requests.get(url)

    data = response.json()

    df = pd.DataFrame(data['data'])

    df.to_csv(
        r"C:\Users\shub2\OneDrive\Desktop\bluestock_mf_capstone/data/raw/{name}.csv",
        index=False
    )

    print(f"{name} saved")

In [ ]:
master_codes = set(
    fund_master['amfi_code']
)

In [ ]:
nav_codes = set(
    nav_history['amfi_code']
)

In [ ]:
missing = master_codes - nav_codes

print(missing)

In [ ]:
report = f"""
Total Fund Codes : {len(master_codes)}
Codes Found In NAV History : {len(master_codes)-len(missing)}
Missing Codes : {len(missing)}
"""

print(report)

In [ ]:
with open(
    r"C:\Users\shub2\OneDrive\Desktop\bluestock_mf_capstone\data\day1_data_quality.txt",
    "w"
) as f:
    f.write(report)